name: Deploy ML Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t ml-model .

    - name: Tag Image
      run: |
        docker tag ml-model:latest ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | sudo docker login --username AWS --password-stdin 687848808647.dkr.ecr.ap-south-1.amazonaws.com
      
            sudo docker pull ${{ secrets.ECR_REPOSITORY }}:latest
      
            sudo docker stop ml-container || true
            sudo docker rm ml-container || true
      
            sudo docker run -d --name ml-container -p 8000:8000 ${{ secrets.ECR_REPOSITORY }}:latest
